AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Description: Stage name to deploy resources to
    AllowedValues:
      - dev
      - stage
      - production

Resources:

  # Lambda Layer for the Lambda functions
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: lambda-layer
      CompatibleRuntimes:
        - java8
    Metadata:
      BuildMethod: java8

  # API Gateway resource
  BooksApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "books-api-${Stage}"
      StageName: !Ref Stage
      Variables:
        LAMBDA_ALIAS: !Ref Stage

  # DynamoDB table
  BooksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: isbn
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      SSESpecification:
        SSEEnabled: true

  #Lambda functions

  GetItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: com.home.amazon.serverless.lambda.GetItemHandler::handleRequest
      Timeout: 20
      MemorySize: 512
      CodeUri: get-item-service
      AutoPublishAlias: !Ref Stage
      Environment:
        Variables:
          TABLE: !Ref BooksTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BooksTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /books/{isbn}
            Method: get
            RestApiId:
              Ref: BooksApi
      Layers:
        - Ref: MyLayer
    Metadata:
      BuildMethod: makefile

  PutItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: com.home.amazon.serverless.lambda.PutItemHandler::handleRequest
      Timeout: 20
      MemorySize: 512
      CodeUri: put-item-service
      AutoPublishAlias: !Ref Stage
      Environment:
        Variables:
          TABLE: !Ref BooksTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref BooksTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /books
            Method: post
            RestApiId:
              Ref: BooksApi
      Layers:
        - Ref: MyLayer
    Metadata:
      BuildMethod: makefile

  DeleteItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: com.home.amazon.serverless.lambda.DeleteItemHandler::handleRequest
      Timeout: 20
      MemorySize: 512
      CodeUri: delete-item-service
      AutoPublishAlias: !Ref Stage
      Environment:
        Variables:
          TABLE: !Ref BooksTable
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:DeleteItem
              Resource: {
                "Fn::Sub": [
                    "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tableName}",
                  {
                    "tableName": {
                      "Ref": "BooksTable"
                    }
                  }
                ]
              }
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /books/{isbn}
            Method: delete
            RestApiId:
              Ref: BooksApi
      Layers:
        - Ref: MyLayer
    Metadata:
      BuildMethod: makefile

  UpdateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: com.home.amazon.serverless.lambda.UpdateItemHandler::handleRequest
      Timeout: 20
      MemorySize: 512
      CodeUri: update-item-service
      AutoPublishAlias: !Ref Stage
      Environment:
        Variables:
          TABLE: !Ref BooksTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref BooksTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /books
            Method: put
            RestApiId:
              Ref: BooksApi
      Layers:
        - Ref: MyLayer
    Metadata:
      BuildMethod: makefile

  # AWS resources for automated build and deployment

  ArtifactBucket:
    Type: 'AWS::S3::Bucket'

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: [ 'sts:AssumeRole' ]
            Effect: Allow
            Principal:
              Service: [ codebuild.amazonaws.com ]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Effect: Allow
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/aws-sam-app-build"
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/aws-sam-app-build:*"
              - Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketLocation"
                Effect: Allow
                Resource:
                  - !GetAtt ArtifactBucket.Arn
                  - !Join [ "", [ !GetAtt ArtifactBucket.Arn, "/*" ] ]
              - Action:
                  - "codebuild:CreateReportGroup"
                  - "codebuild:CreateReport"
                  - "codebuild:UpdateReport"
                  - "codebuild:BatchPutTestCases"
                  - "codebuild:BatchPutCodeCoverages"
                Effect: Allow
                Resource:
                  - !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/aws-sam-app-build-*"

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: aws-sam-app-build
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: public.ecr.aws/sam/build-java8
        Type: LINUX_CONTAINER
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Location: https://github.com/rimironenko/aws-serverless-sam-app.git
        Type: GITHUB
      Artifacts:
        Type: S3
        Location: !Ref ArtifactBucket

Outputs:
  ApiEndpoint:
    Description: "API endpoint"
    Value: !Sub "https://${BooksApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/books"